import React from 'react';
import type { Metadata } from 'next';
import { Inter, Public_Sans } from 'next/font/google';
import './styles/globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-inter',
});

const publicSans = Public_Sans({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font--public-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} bg-gray-100 ${publicSans.variable} overflow-x-hidden`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
